version: "3.9"
services:
  web:
    build: ./web
    ports:
      - "5000:5000"
    volumes:
      - ./shared:/code/shared
      - ./tmp:/code/tmp
  scraper:
    build: ./scraper
    volumes:
      - ./tmp:/code/tmp
      - ./shared:/code/shared
    tty: true