version: "3.9"
services:
#  web:
#    build: ./web
#    ports:
#      - "5000:5000"
#    volumes:
#      - ./tmp:/tmp
  scraper:
    build: ./scraper
    volumes:
      - ./tmp:/tmp
      - ./shared:/shared
    tty: true